<a href="https://colab.research.google.com/github/varmor/DS-Practise/blob/master/numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
'''
The array object class is the foundation of Numpy, and Numpy arrays are like
lists in Python, except that every thing inside an array must be of the
same type, like int or float.
'''
# Change False to True to see Numpy arrays in action
if True:
    array = np.array([1, 4, 5, 8], float)
    print (array)
    print ("")
    array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
    print (array)

[1. 4. 5. 8.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
'''
You can index, slice, and manipulate a Numpy array much like you would with a
a Python list.
'''
# Change False to True to see array indexing and slicing in action
if True:
    array = np.array([1, 4, 5, 8], float)
    print (array)
    print ("")
    print (array[1])
    print ("")
    print (array[:2])
    print ("")
    array[1] = 5.0
    print (array[1])


[1. 4. 5. 8.]

4.0

[1. 4.]

5.0
